#!/usr/bin/env bash
# Regenerate the repo-root NOTICES file aggregating license text for all
# bundled third-party dependencies (npm runtime deps + Rust crates).
#
# Run from repo root. Requires:
#   - pnpm (license data comes from the built-in `pnpm licenses list`, so
#     nothing extra is fetched)
#   - cargo-about with cli feature globally installed:
#     cargo install --locked --features=cli cargo-about
#   - python3 (used for formatting pnpm's license JSON into plain text)
#
# Output: NOTICES at repo root, overwriting any existing file.
#
# Re-run this script after any dependency change (pnpm install, cargo
# add/update, bumping package.json or Cargo.toml versions). The resulting
# NOTICES diff is committable alongside the dep change.

set -euo pipefail

# Resolve to repo root regardless of where the script is invoked from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

OUTPUT="$REPO_ROOT/NOTICES"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# ---- Header ----
cat > "$OUTPUT" <<'EOF'
Skrivro — Third-Party Notices
=============================

Skrivro's own source code is licensed under 0BSD (see LICENSE).

This file aggregates the license notices for all bundled third-party
dependencies so redistributors can satisfy attribution requirements.
Two sections: npm runtime dependencies (the JavaScript side, pulled
in by package.json) and Rust crates (the Tauri / native side, pulled
in by Cargo.toml). Each dep is grouped under its declared license
with full license text.

Regenerated by scripts/gen-notices.sh. If you change dependencies,
re-run the script and commit the resulting NOTICES diff alongside.

EOF

# ---- npm deps ----
echo "================================================================" >> "$OUTPUT"
echo "=== npm package licenses ===" >> "$OUTPUT"
echo "================================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# pnpm's built-in license lister. --prod excludes devDependencies (vite,
# vitest, oxlint, etc.) since those don't ship in the built artifact. The
# JSON is keyed by SPDX license, and each entry gives the package's
# install path(s) rather than a LICENSE file directly, so the Python step
# locates the license text inside each package dir itself.
pnpm licenses list --prod --json > "$TMPDIR/npm.json"

# Format the JSON dump into plain-text sections. Inline python3 avoids a
# separate formatter file, and the heredoc keeps the logic
# self-contained.
python3 - "$TMPDIR/npm.json" <<'PYEOF' >> "$OUTPUT"
import json, sys, os, glob

with open(sys.argv[1]) as f:
    data = json.load(f)

# pnpm groups packages under their license key, so flatten and sort by
# name for stable, diffable output.
packages = [entry for entries in data.values() for entry in entries]

# Prefer a dedicated license file, and fall back to a README, since
# some packages (e.g. font-awesome) carry their terms there instead.
LICENSE_GLOBS = ("LICENSE*", "LICENCE*", "License*", "licence*", "license*", "COPYING*")
README_GLOBS = ("README*", "Readme*", "readme*")

def find_text(pkg_dir, patterns):
    for pat in patterns:
        for path in sorted(glob.glob(os.path.join(pkg_dir, pat))):
            if os.path.isfile(path):
                try:
                    with open(path, encoding="utf-8", errors="replace") as fh:
                        return fh.read().strip()
                except Exception as e:
                    return f"(error reading {os.path.basename(path)}: {e})"
    return ""

for pkg in sorted(packages, key=lambda p: p["name"].lower()):
    name = pkg["name"]
    version = ", ".join(pkg.get("versions", []))
    license_id = pkg.get("license") or "UNKNOWN"
    homepage = pkg.get("homepage")
    pkg_dir = (pkg.get("paths") or [None])[0]

    text = ""
    if pkg_dir and os.path.isdir(pkg_dir):
        text = find_text(pkg_dir, LICENSE_GLOBS) or find_text(pkg_dir, README_GLOBS)

    print("----------------------------------------------------------------")
    print(f"Package: {name} {version}")
    print(f"License: {license_id}")
    if homepage:
        print(f"Homepage: {homepage}")
    print("----------------------------------------------------------------")
    print()
    if text:
        print(text)
    else:
        print("(no LICENSE or README file bundled with this package; see SPDX identifier above)")
    print()
PYEOF

# ---- Rust crates ----
echo "" >> "$OUTPUT"

# cargo-about's config and template live in src-tauri/ because that's
# where Cargo.toml is and where cargo-about expects to discover them by
# default. Change into it for the generate call.
cd "$REPO_ROOT/src-tauri"
cargo about generate about.hbs >> "$OUTPUT"

echo ""
echo "NOTICES regenerated at $OUTPUT"
echo "Review the diff and commit alongside any dep change that triggered the regen."
