#!/usr/bin/env bash
# Regenerate the repo-root NOTICES file aggregating license text for all
# bundled third-party dependencies (npm runtime deps + Rust crates).
#
# Run from repo root. Requires:
#   - license-checker (fetched on demand via npx — kept out of the dependency tree on purpose)
#   - cargo-about with cli feature globally installed:
#     cargo install --locked --features=cli cargo-about
#   - python3 (used for formatting license-checker's JSON into plain text)
#
# Output: NOTICES at repo root, overwriting any existing file.
#
# Re-run this script after any dependency change (npm install, cargo
# add/update, bumping package.json or Cargo.toml versions). The resulting
# NOTICES diff is committable alongside the dep change.

set -euo pipefail

# Resolve to repo root regardless of where the script is invoked from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

OUTPUT="$REPO_ROOT/NOTICES"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# ---- Header ----
cat > "$OUTPUT" <<'EOF'
Skrivro — Third-Party Notices
=============================

Skrivro's own source code is licensed under 0BSD (see LICENSE).

This file aggregates the license notices for all bundled third-party
dependencies so redistributors can satisfy attribution requirements.
Two sections: npm runtime dependencies (the JavaScript side, pulled
in by package.json) and Rust crates (the Tauri / native side, pulled
in by Cargo.toml). Each dep is grouped under its declared license
with full license text.

Regenerated by scripts/gen-notices.sh. If you change dependencies,
re-run the script and commit the resulting NOTICES diff alongside.

EOF

# ---- npm deps ----
echo "================================================================" >> "$OUTPUT"
echo "=== npm package licenses ===" >> "$OUTPUT"
echo "================================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --production excludes devDependencies (eslint, vite, husky, etc.) since
# those don't ship in the built artifact. Default JSON output includes
# `licenses` (SPDX identifier), `licenseFile` (path to the package's
# LICENSE file), and `repository`. We read licenseFile's contents
# ourselves in the Python step — license-checker's --customFormat with
# licenseText has inconsistent behavior across versions, so delegating
# the file read is more robust.
npx --yes license-checker \
    --production \
    --json > "$TMPDIR/npm.json"

# Format the JSON dump into plain-text sections. Inline python3 avoids a
# separate formatter file; the heredoc keeps the logic self-contained.
# The "pkg@version" key is split to get name/version since license-
# checker doesn't expose those as separate fields in default output.
python3 - "$TMPDIR/npm.json" <<'PYEOF' >> "$OUTPUT"
import json, sys, os
with open(sys.argv[1]) as f:
    data = json.load(f)
for key in sorted(data.keys()):
    pkg = data[key]
    # key format: "name@version" or "@scope/name@version"
    if key.startswith("@"):
        name, _, ver = key.rpartition("@")
    else:
        name, _, ver = key.rpartition("@")
    licenses = pkg.get("licenses") or "UNKNOWN"
    license_file = pkg.get("licenseFile")
    text = ""
    if license_file and os.path.isfile(license_file):
        try:
            with open(license_file, encoding="utf-8", errors="replace") as lf:
                text = lf.read().strip()
        except Exception as e:
            text = f"(error reading license file: {e})"
    print("----------------------------------------------------------------")
    print(f"Package: {name} {ver}")
    print(f"License: {licenses}")
    if pkg.get("repository"):
        print(f"Repository: {pkg['repository']}")
    print("----------------------------------------------------------------")
    print()
    if text:
        print(text)
    else:
        print("(no LICENSE file bundled with this package; see SPDX identifier above)")
    print()
PYEOF

# ---- Rust crates ----
echo "" >> "$OUTPUT"

# cargo-about's config and template live in src-tauri/ because that's
# where Cargo.toml is and where cargo-about expects to discover them by
# default. Change into it for the generate call.
cd "$REPO_ROOT/src-tauri"
cargo about generate about.hbs >> "$OUTPUT"

echo ""
echo "NOTICES regenerated at $OUTPUT"
echo "Review the diff and commit alongside any dep change that triggered the regen."
